version: '3.1'
services:
  db:
    restart: always
    image: mysql:8.2
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    restart: always
    platform: linux/amd64
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
      PMA_HOST: db
    depends_on:
      - db
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db
    environment:
      - HOST=${HOST} 
      - DB_USERNAME=${DB_USERNAME} 
      - DB_PASSWORD=${DB_PASSWORD} 
      - DB_DATABASE=${DB_DATABASE} 


